@startuml
participant ":Main" as Main
participant ":Storage" as Storage
participant "f:File" as File
participant "fw:FileWriter" as FileWriter
participant "e:Expense" as Expense
participant "l:Loan" as Loan
hide footbox

Main -> Storage : save(budget, expenses, loans, categoryBudgets)
activate Storage

Storage -> File ** : new File(filePath)
Storage -> File : getParentFile()
activate File
File --> Storage : parentFile
deactivate File

alt parentFile != null && !parentFile.exists()
    Storage -> File : mkdirs()
    activate File
    File --> Storage : created
    destroy File

    note right of Storage
        Throws IOException if
        mkdirs() returns false
    end note
end

create FileWriter
Storage -> FileWriter : new FileWriter(f)
activate FileWriter

Storage -> FileWriter : write("BUDGET | " + budget)

loop for each category in categoryBudgets
    Storage -> FileWriter : write("CATEGORY_BUDGET | " + category + " | " + amount)
end

loop for each l in loans
    Storage --> Loan : getDescription
    activate Loan
    Loan --> Storage : description
    deactivate Loan

    Storage --> Loan : getAmount
    activate Loan
    Loan --> Storage : amount
    deactivate Loan

    Storage --> Loan : getDate
    activate Loan
    Loan --> Storage : date
    deactivate Loan

    Storage -> FileWriter : write("L | " + desc + " | " + amount + " | " + date)
end

loop for each Expense e in expenses
    Storage -> Expense : instanceof check
    activate Expense
    Expense --> Storage : type (F/T/G/O)
    deactivate Expense

    Storage -> Expense : getDescription()
    activate Expense
    Expense --> Storage : description
    deactivate Expense

    Storage -> Expense : getAmount()
    activate Expense
    Expense --> Storage : amount
    deactivate Expense

    Storage -> Expense : getDate()
        activate Expense
        Expense --> Storage : date
        deactivate Expense

    Storage -> FileWriter : write(type + " | " + desc + " | " + amount + "|" + date)
    note over Expense,Loan
    Expense and Loan
    objects are not destroyed
    and will persist in memory
    until application ends

    end note

end



Storage -> FileWriter : close()
destroy FileWriter

Storage --> Main
deactivate Storage
@enduml